services:
  website-valkey:
    container_name: website-valkey
    image: valkey/valkey:latest
    ports:
      - "6379:6379"
    volumes:
      - ./valkey:/data
    restart: always
    healthcheck:
      test: ["CMD", "valkey-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
  website:
    container_name: website
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_TURNSTILE_SITE_KEY=${NEXT_PUBLIC_TURNSTILE_SITE_KEY}
    ports:
      - "3000:3000"
    env_file: .env
    environment:
      - TURNSTILE_SECRET_KEY=${TURNSTILE_SECRET_KEY}
      - CONTACT_EMAIL=${CONTACT_EMAIL}
      - VALKEY_URL=redis://website-valkey:6379
      - GITHUB_PAT=${GITHUB_PAT}
      - WIKIPEDIA_USERNAME=${WIKIPEDIA_USERNAME}
      - LISTENBRAINZ_USERNAME=${LISTENBRAINZ_USERNAME}
    depends_on:
      website-valkey:
        condition: service_healthy
    restart: always
